import {defineConfig} from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                // css
                "resources/scss/app.scss",
                "resources/scss/icons.scss",
                "node_modules/jsvectormap/dist/css/jsvectormap.min.css",
                "node_modules/@simonwep/pickr/dist/themes/monolith.min.css",
                "node_modules/@simonwep/pickr/dist/themes/classic.min.css",
                "node_modules/@simonwep/pickr/dist/themes/nano.min.css",
                "node_modules/choices.js/public/assets/styles/choices.min.css",
                "node_modules/flatpickr/dist/flatpickr.min.css",
                "node_modules/gridjs/dist/theme/mermaid.min.css",
                "node_modules/dropzone/dist/dropzone.css",
                "node_modules/swiper/swiper-bundle.min.css",
                "node_modules/jsvectormap/dist/css/jsvectormap.min.css",
                "node_modules/tippy.js/dist/tippy.css",
                "node_modules/plyr/dist/plyr.css",
                "node_modules/quill/dist/quill.core.css",
                "node_modules/quill/dist/quill.bubble.css",
                "node_modules/quill/dist/quill.snow.css",
                "node_modules/gridjs/dist/theme/mermaid.min.css",

                //js
                "resources/js/config.js",
                "resources/js/head.js",
                "resources/js/app.js",
                "resources/js/pages/apps-calendar.js",
                "resources/js/pages/dashboard.js",
                "resources/js/pages/dashboard-analytics.js",
                "resources/js/pages/apps-inbox.js",
                "resources/js/pages/apps-inbox.js",
                "resources/js/pages/apps-kanban.js",
                "resources/js/pages/apps-tasks.js",
                "resources/js/pages/apps-tasks-details.js",
                "resources/js/pages/form-editor.js",
                "resources/js/pages/pages-profile.js",
                "resources/js/pages/auth-swiper.js",
                "resources/js/pages/form-fileupload.js",
                "resources/js/pages/extended-swiper.js",
                "resources/js/pages/extended-sortable.js",
                "resources/js/pages/extended-ratings.js",
                "resources/js/pages/extended-plyr.js",
                "resources/js/pages/extended-tippy.js",
                "resources/js/pages/icons-remixicons.js",
                "resources/js/pages/icons-lucide.js",
                "resources/js/pages/form-inputmask.js",
                "resources/js/pages/form-color-pickr.js",
                "resources/js/pages/form-flatpickr.js",
                "resources/js/pages/form-choises.js",
                "resources/js/pages/table-gridjs.js",
                "resources/js/pages/apex-area.js",
                "resources/js/pages/apex-bar.js",
                "resources/js/pages/apex-bubble.js",
                "resources/js/pages/apex-candlestick.js",
                "resources/js/pages/apex-column.js",
                "resources/js/pages/apex-heatmap.js",
                "resources/js/pages/apex-line.js",
                "resources/js/pages/apex-mixed.js",
                "resources/js/pages/apex-timeline.js",
                "resources/js/pages/apex-boxplot.js",
                "resources/js/pages/apex-treemap.js",
                "resources/js/pages/apex-pie.js",
                "resources/js/pages/apex-radar.js",
                "resources/js/pages/apex-radialbar.js",
                "resources/js/pages/apex-scatter.js",
                "resources/js/pages/apex-sparklines.js",
                "resources/js/pages/apex-polar-area.js",
                "resources/js/pages/chartjs-area.js",
                "resources/js/pages/chartjs-bar.js",
                "resources/js/pages/chartjs-line.js",
                "resources/js/pages/chartjs-other.js",
                "resources/js/pages/maps-google.js",
                "resources/js/pages/maps-vector.js",
                "resources/js/maps/us-mill-en.js",
                "resources/js/maps/us-lcc-en.js",
                "resources/js/maps/us-aea-en.js",
                "resources/js/maps/in-mill-en.js",
                "resources/js/maps/canada.js",
                "resources/js/maps/iraq.js",
                "resources/js/maps/russia.js",
                "resources/js/maps/spain.js",
            ],
            refresh: true,
        }),
    ],
});
